Algoritmo "CONVERTEDOLAR"

// Descrição   : converte valor em real para dolar (função)
// Autor(a)    : maria eduarda soares
// Data atual  : 12/04/2021
Var
valor,dolar,convertido:real

Inicio
//ENTRADA
escreval("qual o valor do dolar hoje")
leia(dolar)
escreval("qual o valor que voce quer converter")
leia(valor)

//PROCESSAMENTO
convertido<-valor/dolar)

//SAIDA
escreval("o  valor convertido e ",convertido)

Fimalgoritmo