Algoritmo "exercicio10"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : maria eduarda soares
// Data atual  : 17/08/2021
Var
num,cont,fatorial:inteiro

Inicio
escreval("digite um numero inteiro desejado")
leia(num)

cont<-1
fatorial<-1

enquanto cont<=num faca
   fatorial<-fatorial*cont
   cont<-cont+1
fimenquanto
     escreval("o fatorial desse numero e igual a ",fatorial)


Fimalgoritmo
