Algoritmo "exercicio7"
// Descrição   : o progrma vai somar o numero ate que o digito 0 seja digitado
// Autor(a)    : maria eduarda sores
// Data atual  : 17/08/2021
var
 soma, num: inteiro
inicio
num <- 1
soma <- 0
 enquanto num <> 0 faca
   escreval("Digite um numero")
   leia(num)
   soma <- soma + num
 fimenquanto
   escreval("O resultado da soma dos numeros digitados é: ", soma)
   
fimalgoritmo


