Algoritmo "ConverteCelsius"
// Descrição   : converte grau fahrenheint em celsus
// Autor(a)    : maria eduarda soares
// Data atual  : 16/03/2021
Var

celsius, f:real


Inicio
// ENTRADA
ESCREVAL("----Este programa converte fahrenheint em celsus----")
escreval("Digite a temperatura agora la nos EUA")
leia(f)

//PROCESSAMENTO

CElSiUS <- (F - 32)* 5/9

//SAIDA
escreval(f,"graus fahrenheint, convertidos em celsius ficaria:", celsius,"graus celsius")


Fimalgoritmo