Algoritmo "trocadevariaveis"

// Descrição   : TROCAR VARIAVEIS DE LUGAR
// Autor(a)    : Maria eduarda soares
// Data atual  : 16/03/2021
Var
a,b,c :inteiro


Inicio
//ENTRADA
escreval("Digite um valor")
leia(a)
escreval("Digite um valor")
leia(b)

escreval("-----valores invertios------")

c<-a
a<-b
b<-c

//SAIDA
escreval("TROCA")
escreval("valor da A ficou:",a )
escreval("valor da B icou:",b )

Fimalgoritmo